DROP TABLE IF EXISTS hibernate_sequence;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE hibernate_sequence (
    next_val bigint DEFAULT NULL
)
/*!40101 SET character_set_client = @saved_cs_client */;

DROP TABLE IF EXISTS user_role;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE user_role (
  user_id int NOT NULL,
  roles varchar(255) DEFAULT NULL
);

DROP TABLE IF EXISTS usr;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE usr (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
  active boolean DEFAULT NULL,
  email varchar(255) DEFAULT 'qwe123@gmail.com',
  password varchar(255) DEFAULT NULL,
  username varchar(255) DEFAULT NULL,
  date_registration varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
);